sudo: required
services:
  - docker

before_install:
  - docker build -t henriquerusca/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run henriquerusca/react-test npm test -- --coverage

after_success:
  - docker build -t henriquerusca/multi-client -f ./client/Dockerfile ./client
  - docker build -t henriquerusca/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t henriquerusca/multi-server -f ./server/Dockerfile ./server
  - docker build -t henriquerusca/multi-worker -f ./worker/Dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push henriquerusca/multi-client
  - docker push henriquerusca/multi-nginx
  - docker push henriquerusca/multi-server
  - docker push henriquerusca/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-kubernetes
  env: DockerKubernetes-env
  bucket_name: elasticbeanstalk-us-west-2-397384686540
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key:
    secure: $AWS_PASSWORD